<?php

namespace Tests\Feature\App\Http\Controllers;

use Database\Factories\ProductFactory;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

class ThumbnailController extends TestCase
{
    public function test_it_generated_success()
    {
        $size = '500x500';
        $method = 'resize';
        $storage = Storage::disk('images');

        config()->set('thumbnail', ['allowed_sizes' => [$size]]);

        $product = ProductFactory::new()->create();

        $response = $this->get($product->makeThumbnail($size, $method));


        $response->assertOk();

        $storage->assertExists(
            "products/$method/$size" . \Illuminate\Support\Facades\File::basename($product->thumbnail)
        );
    }
}
